[package]
name = "knob-com"
version = "0.1.0"
authors = ["PieMyth <haugenw94@gmail.com>", ]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
find_folder = "0.3.0"
systray = "0.4.0"